### ISSUE TITLE
Error with last commit

### ISSUE THREAD

**Issue by wesraph** [rebane2001/matterport-dl#2]
When I use the last commit I get 
```
python3.9 matterport-dl.py hYfmwRrZH9w
Downloading base page...
Traceback (most recent call last):
  File "/home/raph/sources/viewerdadou/matterport-dl/matterport-dl.py", line 153, in <module>
    initiateDownload(sys.argv[1])
  File "/home/raph/sources/viewerdadou/matterport-dl/matterport-dl.py", line 149, in initiateDownload
    downloadPage(url.split("m=")[-1].split("&")[0])
  File "/home/raph/sources/viewerdadou/matterport-dl/matterport-dl.py", line 130, in downloadPage
    accessurl = re.search(r'"(https://cdn-1.matterport.com/models/.*?/assets/~/{{filename}}\?t=.*?)"', r.text).group(1).replace("{{","{").replace("}}","}")
AttributeError: 'NoneType' object has no attribute 'group'
```

Reverting 172d3d000dc2ffe9254a1f6af154789853588c39 makes everything works again

**Comment by rebane2001** [comment]
Does the final download *actually* work though?

**Comment by wesraph** [comment]
It's still downloading, will tell you when it's finished

**Comment by wesraph** [comment]
Okay it's not working, I will dig a little tomorrow

**Comment by khali3620** [comment]
I am getting the same error with the latest commit

**Comment by rebane2001** [comment]
It seems like Matterport has changed how their site functions and this script will need some rewriting for it to work again

**Comment by khali3620** [comment]
@wesraph did you manage to fix the issue. I would like to help but I don't know enough of web stuff
